# Generated by Django 4.2.7 on 2023-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/img')),
                ('target', models.TextField(default=None, null=True)),
                ('block_1_text', models.TextField(default=None, null=True)),
                ('block_1_image', models.FilePathField(default=None, null=True, path='/img')),
                ('block_2_text', models.TextField(default=None, null=True)),
                ('block_2_image', models.FilePathField(default=None, null=True, path='/img')),
                ('block_3_text', models.TextField(default=None, null=True)),
                ('block_3_image', models.FilePathField(default=None, null=True, path='/img')),
            ],
        ),
    ]
